project:
  type: website
  output-dir: docs

website:
  title: "Jiffy Lesica: Portfolio Junction"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    # Instead of passing image url to title-block-banner, pass true
    # This allows us to use title block space, while controlling style
    # of image in styles.css file
    title-block-banner: true
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





